program DelphiAIKit;

{$APPTYPE CONSOLE}

{$R *.res}

uses
  madExcept,
  madLinkDisAsm,
  madListHardware,
  madListProcesses,
  madListModules,

  FireDAC.Phys.SQLiteWrapper.Stat,
  Dak.Analyze in '..\src\dak.analyze.pas',
  Dak.Analyze.Common in '..\src\dak.analyze.common.pas',
  Dak.Analyze.ProjectRunner in '..\src\dak.analyze.projectrunner.pas',
  Dak.Analyze.UnitRunner in '..\src\dak.analyze.unitrunner.pas',
  Dak.App in '..\src\dak.app.pas',
  Dak.Build in '..\src\dak.build.pas',
  Dak.Build.Runner in '..\src\dak.build.runner.pas',
  Dak.Build.Summary in '..\src\dak.build.summary.pas',
  Dak.Build.Types in '..\src\dak.build.types.pas',
  Dak.Cli in '..\src\dak.cli.pas',
  Dak.CommandOutput in '..\src\Dak.CommandOutput.pas',
  Dak.DeadCodeProfile in '..\src\Dak.DeadCodeProfile.pas',
  Dak.Deps in '..\src\dak.deps.pas',
  Dak.Deps.Runner in '..\src\dak.deps.runner.pas',
  Dak.DfmCheck in '..\src\dak.dfmcheck.pas',
  Dak.DfmInspect in '..\src\dak.dfminspect.pas',
  Dak.DfmText in '..\src\Dak.DfmText.pas',
  Dak.Diagnostics in '..\src\dak.diagnostics.pas',
  Dak.ExitCodes in '..\src\dak.exitcodes.pas',
  Dak.ExternalToolProcess in '..\src\Dak.ExternalToolProcess.pas',
  Dak.FixInsight in '..\src\dak.fixinsight.pas',
  Dak.FixInsightRunner in '..\src\dak.fixinsightrunner.pas',
  Dak.GlobalVars in '..\src\dak.globalvars.pas',
  Dak.GlobalVars.Cache in '..\src\Dak.GlobalVars.Cache.pas',
  Dak.GlobalVars.Model in '..\src\Dak.GlobalVars.Model.pas',
  Dak.GlobalVars.Output in '..\src\Dak.GlobalVars.Output.pas',
  Dak.GlobalVars.Semantics in '..\src\Dak.GlobalVars.Semantics.pas',
  Dak.Lsp in '..\src\dak.lsp.pas',
  Dak.Lsp.Context in '..\src\dak.lsp.context.pas',
  Dak.Lsp.Runner in '..\src\dak.lsp.runner.pas',
  Dak.Lsp.Transport in '..\src\Dak.Lsp.Transport.pas',
  Dak.MacroExpander in '..\src\dak.macroexpander.pas',
  Dak.Messages in '..\src\dak.messages.pas',
  Dak.MsBuild in '..\src\dak.msbuild.pas',
  Dak.Output in '..\src\dak.output.pas',
  Dak.PascalAnalyzer.Artifacts in '..\src\Dak.PascalAnalyzer.Artifacts.pas',
  Dak.PascalAnalyzerRunner in '..\src\dak.pascalanalyzerrunner.pas',
  Dak.Paths in '..\src\Dak.Paths.pas',
  Dak.Project in '..\src\dak.project.pas',
  Dak.Project.BuildParams in '..\src\Dak.Project.BuildParams.pas',
  Dak.Project.Semantics in '..\src\Dak.Project.Semantics.pas',
  Dak.Project.SourceLookup in '..\src\Dak.Project.SourceLookup.pas',
  Dak.RadStudio.Locator in '..\src\Dak.RadStudio.Locator.pas',
  Dak.Refactor in '..\src\Dak.Refactor.pas',
  Dak.Refactor.RenameGuards in '..\src\Dak.Refactor.RenameGuards.pas',
  Dak.Registry in '..\src\dak.registry.pas',
  Dak.RemoveWith in '..\src\Dak.RemoveWith.pas',
  Dak.RemoveWith.Discovery in '..\src\Dak.RemoveWith.Discovery.pas',
  Dak.RemoveWith.Expressions in '..\src\Dak.RemoveWith.Expressions.pas',
  Dak.RemoveWith.Model in '..\src\Dak.RemoveWith.Model.pas',
  Dak.RemoveWith.Output in '..\src\Dak.RemoveWith.Output.pas',
  Dak.RemoveWith.Planner in '..\src\Dak.RemoveWith.Planner.pas',
  Dak.RemoveWith.Resolver in '..\src\Dak.RemoveWith.Resolver.pas',
  Dak.RemoveWith.Source in '..\src\Dak.RemoveWith.Source.pas',
  Dak.RemoveWith.Symbols in '..\src\Dak.RemoveWith.Symbols.pas',
  Dak.RemoveWith.TempPolicy in '..\src\Dak.RemoveWith.TempPolicy.pas',
  Dak.RemoveWith.Transaction in '..\src\Dak.RemoveWith.Transaction.pas',
  Dak.ReportPostProcess in '..\src\dak.reportpostprocess.pas',
  Dak.Resolve in '..\src\dak.resolve.pas',
  Dak.Resolve.Runner in '..\src\dak.resolve.runner.pas',
  Dak.RsVars in '..\src\dak.rsvars.pas',
  Dak.Semantics.Session in '..\src\Dak.Semantics.Session.pas',
  Dak.Settings in '..\src\Dak.Settings.pas',
  Dak.SourceContext in '..\src\dak.sourcecontext.pas',
  Dak.SourceText in '..\src\Dak.SourceText.pas',
  Dak.SymbolMap in '..\src\Dak.SymbolMap.pas',
  Dak.SymbolMap.Api in '..\src\Dak.SymbolMap.Api.pas',
  Dak.SymbolMap.Cache in '..\src\Dak.SymbolMap.Cache.pas',
  Dak.SymbolMap.Context in '..\src\Dak.SymbolMap.Context.pas',
  Dak.SymbolMap.Indexer in '..\src\Dak.SymbolMap.Indexer.pas',
  Dak.SymbolMap.Query in '..\src\Dak.SymbolMap.Query.pas',
  Dak.Types in '..\src\dak.types.pas',
  Dak.Utils in '..\src\dak.utils.pas';

begin
  Halt(TDelphiAIKitApp.Run);
end.
